# Generated by Django 4.1.1 on 2023-01-08 13:03

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='blog/category', verbose_name='Изображение'),
        ),
    ]
